name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Validate prompts.json
      run: node scripts/validate.mjs
    
    - name: Build library
      run: node scripts/build.mjs
    
    - name: Check for required files
      run: |
        test -f prompts.json || (echo "prompts.json missing" && exit 1)
        test -f schema.json || (echo "schema.json missing" && exit 1)
        test -d prompts || (echo "prompts/ directory missing" && exit 1)
        echo "✅ All required files present"
    
    - name: Validate JSON syntax
      run: |
        python3 -m json.tool prompts.json > /dev/null && echo "✅ prompts.json is valid JSON"
        python3 -m json.tool schema.json > /dev/null && echo "✅ schema.json is valid JSON"
        find tags -name "*.json" -exec python3 -m json.tool {} \; > /dev/null && echo "✅ Tag files are valid JSON"

  deploy-pages:
    runs-on: ubuntu-latest
    needs: validate
    if: github.ref == 'refs/heads/main'
    
    permissions:
      contents: read
      pages: write
      id-token: write
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Pages
      uses: actions/configure-pages@v4
    
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./clients/pages
    
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4